// Lista de objetos que contém dados de título, descrição e links das receitas.
let dados = [
    {
        titulo : "Manjar de coco",
        descricao : "O manjar de coco é uma sobremesa tradicional brasileira que encanta paladares há gerações. Sua textura cremosa e sabor suave, com o toque característico do coco, o tornam um doce perfeito para finalizar qualquer refeição. Preparado com ingredientes simples como leite de coco, leite, açúcar e amido de milho, o manjar é versátil e pode ser encontrado em diversas versões, com adição de outros ingredientes como coco ralado, calda de ameixa ou frutas frescas. Sua origem remonta à culinária conventual, e ao longo dos anos, o manjar de coco conquistou um lugar especial no coração dos brasileiros, sendo apreciado por sua simplicidade e sabor inconfundível.",
        linkVideoYT : "https://youtu.be/NR3C48-7aZ8?si=SfPUid2EdbZU8dBo",
        linkReceita : "https://www.tudogostoso.com.br/receita/364-manjar-de-coco.html",
    },
    {
        titulo : "Mousse de Maracujá",
        descricao : "Uma sobremesa refrescante e leve, perfeita para os dias quentes. O mousse de maracujá combina a acidez do maracujá com a cremosidade do leite condensado e do creme de leite, resultando em um doce delicioso e fácil de preparar. Ideal para finalizar uma refeição ou como sobremesa em festas.",
        linkVideoYT : "https://youtu.be/ytMi-OCjFX8?si=SvZNtsDYfM1u2KpI",
        linkReceita : "https://www.tudogostoso.com.br/receita/1599-mousse-de-maracuja.html",
    },
    {
        titulo : "Gelatina Cremosa de Morango",
        descricao : "Uma sobremesa leve e refrescante, perfeita para qualquer ocasião. A gelatina cremosa de morango combina a doçura do morango com a textura gelatinosa, criando um doce delicioso e fácil de preparar. Ideal para festas infantis ou como sobremesa após um almoço em família.",
        linkVideoYT : "https://youtu.be/rlcea8-Gu7E?si=j4BWd62l2UEwDsaM",
        linkReceita : "https://www.oetker.com.br/receitas/r/gelatina-cremosa-de-morango",
    },
    {
        titulo: "Brigadeiro",
        descricao: "O brigadeiro é um doce brasileiro feito com leite condensado, chocolate em pó e manteiga. É um dos doces mais populares do Brasil e é muito fácil de fazer.",
        linkVideoYT: "https://youtu.be/B1neuYtLVKE?si=gd3zPJJp1ojLWMwt",
        linkReceita: "https://www.tudogostoso.com.br/receita/114-brigadeiro.html",
    },
    {
        titulo: "Pudim de leite",
        descricao: "O pudim de leite é uma sobremesa cremosa e caramelizada feita com leite condensado, leite, ovos e açúcar.",
        linkVideoYT: "https://youtu.be/UDYZqGqOdwA?si=Iq3cwvZZUUbKXvB1",
        linkReceita: "https://www.tudogostoso.com.br/receita/3687-pudim-de-leite-condensado.html",
    },
    {
        titulo: "Bolo de chocolate",
        descricao: "O bolo de chocolate é um clássico da confeitaria, perfeito para qualquer ocasião.",
        linkVideoYT: "https://youtu.be/QFMxJWh3mqE?si=S_s3wDXYZyDsJwKC",
        linkReceita: "https://www.tudogostoso.com.br/receita/951-bolo-de-chocolate-molhadinho.html",
    },
    {
        titulo: "Pavê",
        descricao: "O pavê é uma sobremesa em camadas com bolacha maizena, creme e frutas.",
        linkVideoYT: "https://youtu.be/T4zigJcD7aA?si=leUeWWFFvK2rnThZ",
        linkReceita: "https://www.tudogostoso.com.br/receita/23026-pave-de-bolacha-de-maizena.html",
    },
    {
        titulo: "Mousse de chocolate",
        descricao: "O mousse de chocolate é uma sobremesa leve e aerada, perfeita para os amantes de chocolate.",
        linkVideoYT: "https://youtu.be/sJHQcPqIJ1g?si=Lds-rUZ2W-a1UQuX",
        linkReceita: "https://www.tudogostoso.com.br/receita/2513-mousse-de-chocolate.html",
    },
    {
        titulo: "Beijinho",
        descricao: "O beijinho é um doce brasileiro feito com leite condensado, coco ralado e manteiga. Sua textura macia e sabor suave o tornam uma opção clássica para festas e eventos.",
        linkVideoYT: "https://youtu.be/A13owoCNOKU?si=XsKUdORDHRNizOcL",
        linkReceita: "https://www.tudogostoso.com.br/receita/1252-beijinho.html",
    },
    {
        titulo: "Brownie",
        descricao: "O brownie é um bolo de chocolate denso e úmido, originário dos Estados Unidos. É perfeito para acompanhar uma bola de sorvete.",
        linkVideoYT: "https://youtu.be/I2VUOvU-xTQ?si=KiqHqNQErnANZCt1",
        linkReceita: "https://www.tudogostoso.com.br/receita/11659-brownie-super-facil.html",
    },
    {
        titulo: "Torta de limão",
        descricao: "A torta de limão é uma sobremesa cítrica e refrescante, com base de biscoito e recheio cremoso de limão.",
        linkVideoYT: "https://youtu.be/X3dtT2bGrys?si=nGFjnIvKvhJgR_xE",
        linkReceita: "https://www.urbano.com.br/torta-de-limao",
    },
    {
        titulo: "Cheesecake",
        descricao: "Sobremesa americana com base de biscoito e recheio cremoso de queijo.",
        linkVideoYT: "https://youtu.be/tspdJ6hxqnc?si=gXwAhiTpbfUV-cgi",
        linkReceita: "https://www.tudogostoso.com.br/receita/55441-cheesecake-com-molho-de-morangos.html",
    },
    {
        titulo: "Pavlova",
        descricao: "Leve como uma nuvem, a pavlova é uma sobremesa australiana que encanta com sua crosta crocante e interior macio. Perfeita para festas e ocasiões especiais.",
        linkVideoYT: "https://youtu.be/tGLvLum336g?si=0Nm89qQyZctCKEx3",
        linkReceita: "https://www.tudogostoso.com.br/receita/136476-pavlova.html",
    },
    {
        titulo: "Tiramisu",
        descricao: "Um clássico italiano que combina biscoitos de café, queijo mascarpone e cacau em pó. Uma explosão de sabor em cada garfada!",
        linkVideoYT: "https://youtu.be/gZfLLLb4K5c?si=Nq9-Zu4Hb5TLh4Lh",
        linkReceita: "https://www.tudogostoso.com.br/receita/11500-verdadeiro-tiramisu-italiano.html",
    },
    {
        titulo: "Três Leites",
        descricao: "Macio e saboroso, o bolo de três leites é um clássico latino-americano. Molhadinho e com uma cobertura cremosa, é uma delícia!",
        linkVideoYT: "https://youtu.be/1FziM92AeE4?si=UGWQ9-p2STZ2B3LN",
        linkReceita: "https://www.tudogostoso.com.br/receita/54965-bolo-3-leites.html",
    },
    {
        titulo: "Macarons",
        descricao: "Delicados e coloridos, os macarons são biscoitos franceses que encantam pela beleza e sabor. Experimente diferentes combinações de sabores.",
        linkVideoYT: "https://youtu.be/6wWQiU_uLbg?si=MQo6lW6SC7BMCqdO",
        linkReceita: "https://www.tudogostoso.com.br/receita/127330-macaron.html",
    },
    {
        titulo: "Profiteroles",
        descricao: "Pequenos bolinhos de massa choux recheados com creme e cobertos com chocolate. Uma verdadeira explosão de sabor em cada mordida!",
        linkVideoYT: "https://youtu.be/5c1yfT6GZ6w?si=k4_4uFtgnnSvWU1B",
        linkReceita: "https://www.tudogostoso.com.br/receita/171883-profiteroles.html",
    },
    {
        titulo: "Brownie Vegano com Chocolate Amargo",
        descricao: "Um clássico reconquistado! Esse brownie vegano é úmido e intenso, feito com chocolate amargo de alta qualidade e ingredientes naturais. Perfeito para acompanhar um bom café.",
        linkVideoYT: "https://youtu.be/QF-6ESzd9Yw?si=zKFIw1pKdsSLXZw3",
        linkReceita: "https://presuntovegetariano.com.br/receitas/brownie-vegano/",
      },
      {
        titulo: "Cheesecake de Maracujá Vegano",
        descricao: "Refrescante e cremoso, esse cheesecake vegano de maracujá é a sobremesa ideal para os dias quentes. A base crocante de biscoito e o recheio levemente ácido do maracujá formam uma combinação perfeita.",
        linkVideoYT: "https://youtu.be/eLryi2oJI3E?si=BFK8ScTK_TQkeIYP",
        linkReceita: "https://greendelights.pt/2022/08/11/cheesecake-de-maracuja-vegan/",
      },
      {
        titulo: "Mousse de Chocolate Vegano com Abacate",
        descricao: "Cremoso e nutritivo, esse mousse de chocolate vegano leva abacate em sua composição, o que garante uma textura aveludada e um sabor inigualável. Ideal para quem busca uma sobremesa vegana e saudável.",
        linkVideoYT: "https://youtu.be/6YMnyKZQCFs?si=jXDe9PfMUmlal-3-",
        linkReceita: "https://www.tudogostoso.com.br/receita/197580-mousse-de-chocolate-vegano.html",
      },
      {
        titulo: "Pavlova Vegana com Frutas Vermelhas",
        descricao: "Leve e sofisticada, a pavlova vegana é perfeita para ocasiões especiais. A base crocante e o merengue vegano combinam perfeitamente com as frutas vermelhas frescas.",
        linkVideoYT: "https://youtu.be/GCvzzJiljS4?si=jAQ5kifzH4CTRLs5",
        linkReceita: "https://www.gorenje.com.br/life-simplified/alimentacao/receitas/mini-pavlova-vegano",
      },
      {
        titulo: "Bolo de Cenoura Vegano com Cobertura de Chocolate",
        descricao: "Úmido e saboroso, esse bolo de cenoura vegano é um clássico da culinária vegana. A cobertura de chocolate amargo complementa perfeitamente o sabor suave da cenoura.",
        linkVideoYT: "https://youtu.be/W_Pgv27bdJI?si=TVmMoYvTRdlJQmWt",
        linkReceita: "https://www.maeterra.com.br/r/bolo-de-cenoura-com-chocolate-vegano.html/232308",
      },
      {
        titulo: "Quindim Vegano",
        descricao: "Um clássico brasileiro com uma versão vegana irresistível! Esse quindim vegano é feito com leite de coco e tem um sabor caramelizado que encanta.",
        linkVideoYT: "https://youtu.be/gzsOVEAy4ns?si=C5JPMKLTiIoqfSGq",
        linkReceita: "https://zonacerealista.com.br/blogs/blog/quindim-vegano?srsltid=AfmBOoojr3flA9AsKSHVbBPuX1eC5G5xnHiIX0b3mZvHCVYzjs0shrqs",
      },
      {
        titulo: "Tiramisu Vegano",
        descricao: "Uma releitura vegana do clássico italiano, esse tiramisu é feito com biscoitos de café, creme de coco e cacau em pó. Uma explosão de sabor em cada garfada!",
        linkVideoYT: "https://youtu.be/jeKuT_XHWGg?si=WqAx1hZdT3pylnnN",
        linkReceita: "https://www.receiteria.com.br/receita/tiramisu-vegano/",
      },
      {
        titulo: "Trufas Veganas de Chocolate",
        descricao: "Deliciosas e fáceis de fazer, essas trufas veganas são perfeitas para presentear ou para saborear em qualquer ocasião. Experimente com diferentes sabores de chocolate.",
        linkVideoYT: "https://youtu.be/hlmaK4s50Hc?si=XdstKfIMg-nhIX0w",
        linkReceita: "https://vegcomcarinho.com.br/2023/04/07/como-fazer-trufa-de-chocolate-vegana/",
      },
      {
        titulo: "Brownie de Chocolate Sem Glúten",
        descricao: "Intenso e úmido, esse brownie é feito com farinha de amêndoa e cacau em pó. Perfeito para acompanhar um sorvete de creme ou uma bola de frutas vermelhas.",
        linkVideoYT: "https://youtu.be/eOYAW8hoNcM?si=paJmyeAJW46WSYZO",
        linkReceita: "https://www.tudogostoso.com.br/receita/177339-brownie-sem-gluten.html",
      },
      {
        titulo: "Cheesecake de Frutas Vermelhas Sem Glúten",
        descricao: "Refrescante e leve, esse cheesecake é feito com base de biscoito de maisena e recheio cremoso de cream cheese. Perfeito para os dias quentes.",
        linkVideoYT: "https://youtu.be/M5rljZPoaeA?si=HU7uQd8X6ymvJ5ug",
        linkReceita: "https://www.schaer.com/pt-br/r/cheesecake-frutas-vermelhas",
      },
      {
        titulo: "Mousse de Maracujá Sem Glúten",
        descricao: "Cremoso e leve, esse mousse é feito com leite de coco e polpa de maracujá. Uma explosão de sabor em cada colherada!",
        linkVideoYT: "https://youtu.be/1uK_uJKHpoM?si=cF8nzpVM_sKfPjPu",
        linkReceita: "https://menusemgluten.com/2018/01/08/torta-mousse-de-maracuja-sem-gluten/",
      },
      {
        titulo: "Torta de Limão Sem Glúten",
        descricao: "Cítrica e refrescante, essa torta é feita com base de biscoito de maisena e um delicioso creme de limão. Perfeita para o verão!",
        linkVideoYT: "https://youtu.be/4L60fUgPGC0?si=JvjiyIlCC41jb89f",
        linkReceita: "https://minhasreceitinhas.com.br/receita/torta-de-limao-sem-gluten-e-sem-lactose/",
      },
      {
        titulo: "Bolo de Coco Sem Glúten",
        descricao: "Úmido e saboroso, esse bolo é feito com farinha de coco e leite de coco. Ideal para quem ama o sabor do coco.",
        linkVideoYT: "https://youtu.be/wHJOwt7J8mE?si=56SI8LN9KKdms4sw",
        linkReceita: "https://amorpelacomida.com.br/bolo-de-coco-cremoso/",
      },
      {
        titulo: "Cookies de Aveia e Chocolate Chips Sem Glúten",
        descricao: "Macios e deliciosos, esses cookies são perfeitos para um lanche rápido e prático. Feitos com aveia em flocos e gotas de chocolate, são irresistíveis!",
        linkVideoYT: "https://youtu.be/vXQYZ-jENRo?si=mGjC69Ygpo7s1z5U",
        linkReceita: "https://receitas.globo.com/dietas/sem-gluten/cookies-de-aveia-com-chocolate-sem-gluten-549cb1f14d38852e0d000042.ghtml",
      },
      {
        titulo: "Pudim de Leite Condensado Sem Glúten",
        descricao: "Clássico e cremoso, esse pudim é feito com leite de coco e leite condensado. Uma sobremesa simples e deliciosa para qualquer ocasião.",
        linkVideoYT: "https://youtu.be/LkDs-lQLdsc?si=nH2VypS9WjA9vx-U",
        linkReceita: "https://www.tudogostoso.com.br/receita/314586-pudim-de-leite-de-coco-sem-lactose-e-sem-gluten.html",
      },
      {
        titulo: "Mousse de Chocolate Sem Glúten",
        descricao: "Suave e cremoso, esse mousse é feito com chocolate branco e leite de coco. Perfeito para os amantes de chocolate branco.",
        linkVideoYT: "https://youtu.be/AbVR80nh4m4?si=iLJ57BR89WyfdyO4",
        linkReceita: "https://cybercook.com.br/receitas/doces/mousses-e-pudins/receita-de-mousse-de-chocolate-sem-gluten-123209",
      },
      {
        titulo: "Torta de Maçã Sem Glúten",
        descricao: "Quentinha e reconfortante, essa torta é feita com maçãs caramelizadas e uma cobertura crocante. Ideal para os dias frios.",
        linkVideoYT: "https://youtu.be/gm8Dr_l8IxU?si=2uGF6lnI84ZMAU8y",
        linkReceita: "https://www.tudogostoso.com.br/receita/189168-torta-de-maca-sem-gluten.html",
      },
      {
        titulo: "Cupcakes de Cenoura Sem Glúten",
        descricao: "Úmidos e saborosos, esses cupcakes são feitos com farinha de amêndoa e cenoura ralada. Perfeitos para festas e comemorações.",
        linkVideoYT: "https://youtu.be/q8jaCK-9jlg?si=ya5S8aoTBwUD0Ypr",
        linkReceita: "https://casacaroba.com/muffin-de-cenoura-sem-gluten",
      },
];
